### ISSUE TITLE
[Frontend] Integration the Influencers Signup with Backend

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#10]
## Description
Current frontend page is static, integrate the [Influencers-Signup](https://github.com/Kajol-Kumari/InfluMart/blob/main/influmartFrontend/screens/InfluencerRegistrationForm.js) page with its backend API  -
https://github.com/Kajol-Kumari/InfluMart/blob/main/backend/controllers/influencerController.js#L12

**Comment by Vidip-Ghosh** [comment]
I would like to work on this issue.

**Comment by Kajol-Kumari** [comment]
@Vidip-Ghosh please go ahead, Happy Learning:)

**Comment by Shivam2534** [comment]
Hello Sir,

My name is Shivam Kanchole, and I am a fourth-year student at IIT Roorkee. I find this issue both interesting and challenging. Additionally, I have worked on similar projects in the past. Could you please assign this issue to me?

Thank you.

Best regards,
Shivam Kanchole

**Comment by RohitGupta1237** [comment]
@Vidip-Ghosh  hey are u working on this ?

**Comment by RohitGupta1237** [comment]
@Vidip-Ghosh  ok , would it be possible to get this issue fix little fast pls.

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh ok , would it be possible to get this issue fix little fast pls.

Okay I will try.

**Comment by RohitGupta1237** [comment]
@Shivam2534  which issue u r working on currently ?

**Comment by Hemu21** [comment]
@RohitGupta1237  can you please assign this to me
