### ISSUE TITLE
[Frontend] Redesign Home page

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#101]
## Description
The current homepage looks dull, need simple and attractive rennovation. This issue is kinda open to all. All the genuine home-page renovation proposal will get 1 point and then one final selected proposal's implementation should be implemented and will be given `level1`

**Comment by coderight1** [comment]
is it open for gssoc students only or for all ??

**Comment by RohitGupta1237** [comment]
@coderight1  its open for all

**Comment by n-keerthi-gayathri** [comment]
@Kajol-Kumari please assign me under GSSOC'24.

**Comment by shivansh84ya** [comment]
please assign me this task

**Comment by RamakrushnaBiswal** [comment]
hi @Kajol-Kumari can i work on it , i can fix it with in one day
