### ISSUE TITLE
[Frontend] Redesign and fix the BrandList Page 

### ISSUE THREAD

**Issue by Lanthoiba2022** [Kajol-Kumari/InfluMart#103]
Currently the Brandlist page is not properly design. It doesn't have the right heading , the icons are not matching and incorrect and the display picture of brands are also not correct. I want to fix this BrandList Page as describe/illustrate in the Figma file.
![image](https://github.com/Kajol-Kumari/InfluMart/assets/96556290/c033e9f7-fb2e-45f1-8fb7-aefbb94aff4e)

**Comment by Lanthoiba2022** [comment]
Please assign me this issue. I'll fix it ASAP.

**Comment by RohitGupta1237** [comment]
@Lanthoiba2022  who?

**Comment by Lanthoiba2022** [comment]
@RohitGupta1237 Yes. is there any prerequisite?

**Comment by RohitGupta1237** [comment]
choose any existing issue u want to work on

**Comment by Lanthoiba2022** [comment]
Ok sure.
