### ISSUE TITLE
[Frontend] Integration of analytics.js with backend completely

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#105]
fetching data from api and Integration of analytics.js with backend completely is to be done in this task
In analytics page only upper portion of api needs to intgrated involving name dp category...... graphs part and rest  is already integrated .... Adding price for social media platforms below the graphs analytics.js completely from backend for all platforms stored in db.
<img width="493" alt="Screenshot 2024-06-28 at 11 05 12 AM" src="https://github.com/Kajol-Kumari/InfluMart/assets/97328133/a2be062f-74f7-4c87-bdff-36a5e5130f4f">

**Comment by shivansh84ya** [comment]
Could you please assign this issue to me?

**Comment by RohitGupta1237** [comment]
@shivansh84ya hey assigned would it be possible to wrap this asap we are little short of time

**Comment by UtkarshBirla28** [comment]
@RohitGupta1237 Assign it to me i will resolve it in only 2-3 days

**Comment by RohitGupta1237** [comment]
@UtkarshBirla28  assigned ..hey we dont have much time pls try to wrap it in 1-2 day there is not much to integrate graphs are already integrated ...if we can cnnect on meet for 5 min ?

**Comment by shivansh84ya** [comment]
Hello Utkarsh,

Thank you for reaching out to me regarding the assignment.I confirm that I
will take on the #191 issue and work diligently to resolve it within the
specified timeframe.
If you have any specific instructions or requirements, please feel free to
let me know.

Best regards,
Shivansh Chourasia

**Comment by RohitGupta1237** [comment]
@UtkarshBirla28 @shivansh84ya  hey both of u can do one page each will create separate issues

**Comment by shivansh84ya** [comment]
Hi Rohit,

Yes, I am willing to work on one page. Sign up with GitHub done??

Best regards,
Shivansh Chourasia

**Comment by RohitGupta1237** [comment]
@shivansh84ya  will assign u userprofile.js okay will that work for u ?

**Comment by RohitGupta1237** [comment]
@shivansh84ya  new issue created..will assign u that there

**Comment by RohitGupta1237** [comment]
@UtkarshBirla28  hey u can work on this issue

**Comment by UtkarshBirla28** [comment]
@RohitGupta1237 yes ok i only have to work on analytics  page right ??

**Comment by RohitGupta1237** [comment]
@UtkarshBirla28  yes

**Comment by UtkarshBirla28** [comment]
@RohitGupta1237 Sir which API u r talking about in the title ??

**Comment by RohitGupta1237** [comment]
Can we connect on meet ? For 5 min now

**Comment by UtkarshBirla28** [comment]
@RohitGupta1237 Sorry sir but i am in college right now trying to code in middle of the lecture :)

you will notbe able to hear me at all

**Comment by UtkarshBirla28** [comment]
@RohitGupta1237  can u explain in detail here only ?

i will try to figure it out

**Comment by RohitGupta1237** [comment]
@UtkarshBirla28   in influencerRoutes there is get profile by id end point which will give u desired result

**Comment by RohitGupta1237** [comment]
@UtkarshBirla28  
<img width="146" alt="Screenshot 2024-06-28 at 10 42 51 AM" src="https://github.com/Kajol-Kumari/InfluMart/assets/97328133/0259fd5d-b93e-402f-a517-82593eab1930">


the lower part is lready integrated u have to integrate this only name dp categroy whatever that api is returning

**Comment by Hemu21** [comment]
@RohitGupta1237  can you please assign this to me.

**Comment by Hemu21** [comment]
@RohitGupta1237 can you please assign thi sto me.

**Comment by RohitGupta1237** [comment]
@UtkarshBirla28  hey would it be possible for u to contribute on other issue ...we are little out of time...

**Comment by UtkarshBirla28** [comment]
@RohitGupta1237 i was working on it for more than an hour :)

**Comment by RohitGupta1237** [comment]
@UtkarshBirla28  i can understand but we need to get it done by 1 i hope u understand pls

**Comment by UtkarshBirla28** [comment]
@RohitGupta1237 sure :)
