### ISSUE TITLE
[Frontend] Completing the Influencer Setting Profile "admin panel" UI with connected pages 

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#109]
Completing the Influencer Setting Profile "admin panel" UI with connected pages where when user will click manage profile the form similar to influcner sign up form will open with changed heading and file named manageproilfe.js and it would have less fields as compared influcner sign up form and in this there will be a pencil icon to show editable fields and if some made chnges in social media handles the logic will remain same as it is and delete accoutn ,  logout , buttons will have pages separately named as logout.js and deleteaccount.js and help center and contact centre also pages included in it

**Comment by Hemu21** [comment]
@RohitGupta1237  can you please assign this to me
