### ISSUE TITLE
[Frontend] Integration the Brand /Influencer Login with Backend 

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#11]
## Description
Current frontend page is static, integrate the [Login](https://github.com/Kajol-Kumari/InfluMart/blob/main/influmartFrontend/screens/LoginPage.js) page with the backend API -
- https://github.com/Kajol-Kumari/InfluMart/blob/main/backend/controllers/influencerController.js#L58
- https://github.com/Kajol-Kumari/InfluMart/blob/main/backend/controllers/brandController.js#L31 

P.S - You might need to introduce any flag on frontend to determine which api to call during login

**Comment by BHS-Harish** [comment]
Hey @Kajol-Kumari @RohitGupta1237 

I'm interested to working on this issue.

**Comment by Kajol-Kumari** [comment]
@BHS-Harish  please go ahead with this issue, happy learning :)

**Comment by RohitGupta1237** [comment]
@BHS-Harish any doubt with this task?

**Comment by Shivam2534** [comment]
Hello Sir,

My name is Shivam Kanchole, and I am a fourth-year student at IIT Roorkee. I find this issue both interesting and challenging. Additionally, I have worked on similar projects in the past. Could you please assign this issue to me?

Thank you.

Best regards,
Shivam Kanchole

**Comment by RohitGupta1237** [comment]
@Shivam2534  hey assigned you this ...u can work on this ...happy learning
