### ISSUE TITLE
[Frontend] Integration of userprofile.js with backend completely

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#123]
look at inlfuncer data base and integrate all fields with userprofile.

<img width="275" alt="Screenshot 2024-06-28 at 11 45 57 AM" src="https://github.com/Kajol-Kumari/InfluMart/assets/97328133/53f9df1b-3886-4813-b4b5-b0cf1ac168d6">

instead of pricing spot services rename them as instagram youtube facebook 
for instagram 
replace basic with followers
replace standard with price per post 
 replace premium with avg likes 
 replace product post with total collaborations done 
 replace story post with total interests received 
 replace reel with city contributing max viewers
and  add category 
add membersReachability
add avgage  data 
add avg comments  data

for youtube 
replace basic with subscribercount
replace standard with price per video
 replace premium with viewscount
  replace product post with total collaborations done 
 replace story post with total interests received 
 replace reel with videocount

for facebook 
replace basic with followers
replace standard with price per video
 replace premium with likes
  replace product post with total collaborations done 
 replace story post with total interests received 

all these things are in db foe each platform

**Comment by Hemu21** [comment]
@RohitGupta1237  can you please assign this to me.
