### ISSUE TITLE
[Bug] Recent Highlight Section Not working

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#132]
## Description
The data getting stored in db is like `lastPosts` for insta and `lastPost` for youtube but the `popularPosts` is getting used to render the recent highlights which is causing it not to appear on the page - https://github.com/Kajol-Kumari/InfluMart/blob/main/frontend/screens/Analytics/Analytics.js#L229

Fix the recent highlight section
<img width="979" alt="Screenshot 2024-06-29 at 11 50 58 AM" src="https://github.com/Kajol-Kumari/InfluMart/assets/44888949/27c1cc16-2acb-4126-9506-46cb2700c87a">

**Comment by Hemu21** [comment]
@Kajol-Kumari  it is working you can see the preview in pr: 133
