### ISSUE TITLE
Adding Multilanguage Facility 

### ISSUE THREAD

**Issue by Ojas-Arora** [Kajol-Kumari/InfluMart#144]
@Kajol-Kumari I want to add a multilanguage button in this page. Kindly assign this issue to me.

**Comment by RohitGupta1237** [comment]
@Ojas-Arora  which page?

**Comment by Ojas-Arora** [comment]
Main Page sir

**Comment by RohitGupta1237** [comment]
@Ojas-Arora assigned ...u will be working on homepage.js file?

**Comment by Ojas-Arora** [comment]
Yes sir

**Comment by RohitGupta1237** [comment]
@Ojas-Arora  okay ...can i add more task with this task would u do it if possible

**Comment by Ojas-Arora** [comment]
Likewise can u tell which task?

**Comment by RohitGupta1237** [comment]
will share u figma and static code for contact us about us brands and influencers services u have to just make them responsive and add them to homepage buttons ..currenlty those 4 options are not workable

**Comment by RohitGupta1237** [comment]
or u can do this task making blue color button consistent all across ...cureenlt some blue butoons are light blue some are dark if u can make them consistent 

u can choose any task

**Comment by Ojas-Arora** [comment]
I can do both of thses firstly I will do the upper one.

**Comment by RohitGupta1237** [comment]
@Ojas-Arora  great adding that issue with this then

**Comment by Ojas-Arora** [comment]
@RohitGupta1237 Sir make independent issues.

**Comment by RohitGupta1237** [comment]
@Ojas-Arora  ok

**Comment by RohitGupta1237** [comment]
@Ojas-Arora  sorry to bother could u take #37 or #46 now we need them to wrap up before any other issue ?

**Comment by Ojas-Arora** [comment]
I would like to work on both but firstly I would like to try #37.

**Comment by RohitGupta1237** [comment]
@Ojas-Arora  can u try 46 pls first

**Comment by Ojas-Arora** [comment]
ok

**Comment by Ojas-Arora** [comment]
@RohitGupta1237 Please provide me the steps to run this repo in local.

**Comment by Ojas-Arora** [comment]
> @RohitGupta1237 Please provide me the steps to run this repo in local.

@RohitGupta1237 @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
@Ojas-Arora  just follow the readme for each frontend and backend - https://github.com/Kajol-Kumari/InfluMart/blob/main/backend/README.md https://github.com/Kajol-Kumari/InfluMart/blob/main/frontend/README.md
