### ISSUE TITLE
making 4 mentioned buttons workable and connected and responsive ...they should work for all screen size

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#146]
will share u figma and static code for contact us about us brands and influencers services u have to just make them responsive and add them to homepage buttons ..currenlty those 4 options are not workable in homepage.js file
 and also fix these ui 
 
renaming some home page components
fixing influncer list and brand list
adding dark theme to app
renaming in influencer registartion form

**Comment by BHS-Harish** [comment]
@RohitGupta1237 

Please assign me the issue
