### ISSUE TITLE
Feat : Redesigning the join the community page

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Kajol-Kumari/InfluMart#150]
it is too large for desktop view it must be small 

![image](https://github.com/Kajol-Kumari/InfluMart/assets/125277258/56efba77-42f2-462a-81d9-42b4994b6707)

**Comment by RohitGupta1237** [comment]
@RamakrushnaBiswal  hey if u can work on influncerlist ad brand assosciated page ...redesign it currently it looks very basic

**Comment by RohitGupta1237** [comment]
@RamakrushnaBiswal 
<img width="1440" alt="Screenshot 2024-06-30 at 7 46 07 PM" src="https://github.com/Kajol-Kumari/InfluMart/assets/97328133/7d0e9fa5-7b78-454a-9fbb-a302592e7478">
<img width="1440" alt="Screenshot 2024-06-30 at 7 46 22 PM" src="https://github.com/Kajol-Kumari/InfluMart/assets/97328133/8e171ae5-4859-4455-a43e-ce3fd01dacd5">

**Comment by RamakrushnaBiswal** [comment]
yes i can @RohitGupta1237

**Comment by RohitGupta1237** [comment]
@RamakrushnaBiswal  ok so i will edit this issue and make it according to task ..but page should be responsive and integrated with backend like it is dont redo complete page make changes here only to avoid any functioanltiy change
