### ISSUE TITLE
Adding the on hover and tilty effects to  the  cards.

### ISSUE THREAD

**Issue by happyrao78** [Kajol-Kumari/InfluMart#151]
It will enhance the UI as well as the better user experience.

**Comment by RohitGupta1237** [comment]
@happyrao78  which page >?

**Comment by RohitGupta1237** [comment]
@happyrao78 can u work on brandassosciated page and influencerlist page.js? need its better look

**Comment by happyrao78** [comment]
> @happyrao78 can u work on brandassosciated page and influencerlist page.js? need its better look

Sure.

**Comment by happyrao78** [comment]
> @happyrao78 which page >?
Home Page

**Comment by RohitGupta1237** [comment]
@happyrao78 cool will assign u this issue

**Comment by happyrao78** [comment]
> @happyrao78 cool will assign u this issue

Kindly add the labels too and tell me in brief what you want me to do in brand and explore section ?

**Comment by happyrao78** [comment]
kindly assign the levels  label.
