### ISSUE TITLE
Adding a preloader to website.

### ISSUE THREAD

**Issue by happyrao78** [Kajol-Kumari/InfluMart#153]
Adding preloader to website using GSAP.

**Comment by RohitGupta1237** [comment]
@happyrao78  u an add this

**Comment by happyrao78** [comment]
@RohitGupta1237 assign me the level label.

**Comment by RohitGupta1237** [comment]
@happyrao78  workign 0n it ?

**Comment by happyrao78** [comment]
> @happyrao78 workign 0n it ?

Yes.
