### ISSUE TITLE
[frontend] adding a field of name for brand and influencer in their respective registration forms without disturbing ui.

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#156]
adding a field of name for brand and influencer in their respective registration forms without disturbing ui and a mobile no for influencers in their form with a button to verify it and a category dropdown similar to brand registration form making no disturbances in original ui (get this button from form of social media handles)

**Comment by BHS-Harish** [comment]
@RohitGupta1237 

Please assign me the issue
