### ISSUE TITLE
integrate messaging backend with frontend.

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#180]
integrate messaging backend with frontend.

**Comment by siddharthisrani** [comment]
Hii @RohitGupta1237  Can you please give me more details about this? and assign this to me

**Comment by RohitGupta1237** [comment]
@siddharthisrani  would u like to work on #184

**Comment by Hemu21** [comment]
@RohitGupta1237  can you please assign me.
