### ISSUE TITLE
[frontend] After verification of Youtube account, it's not able to redirect to the app

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#185]
**Note - Before starting to work on this issue, share your emailId so that I can whitelist it for you to test the oAuth feature**
## Description
Go to influencer registration form -> click on verify icon of youtube -> enter emailId and passworkd -> you will be able to be logged in but redirection doesn't happen
<img width="1906" alt="Screenshot 2024-07-04 at 11 33 22 PM" src="https://github.com/Kajol-Kumari/InfluMart/assets/44888949/c26c729e-4b2e-4f58-a2e7-17529a5d3fa6">

Below is the redirect urls added in the google cloud
<img width="649" alt="Screenshot 2024-07-04 at 11 41 06 PM" src="https://github.com/Kajol-Kumari/InfluMart/assets/44888949/1642d590-32ad-4c71-9eb5-dee982dd51a1">

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign me.

**Comment by Hemu21** [comment]
@Kajol-Kumari  my mail gujjalahemanthkumar789@gmail.com

**Comment by Kajol-Kumari** [comment]
it was a tidious bug so updating the level
