### ISSUE TITLE
new flow to add in app 

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#186]
add + in brandprofile bottom bar-> collab form-> press post button ---> collab posted in app page 

collab page-> all collab list-> collab detail page -> apply button-> collab request sent from influcner to brand-> notification page in brandprofle where all request will be shown-> accept/reject-> hi sent to both brand and influencer 

This will be created in multiple issue ...sleect ur work will assign u that task Figma ui will be shared...making of ui backned then integration ...which ever task u want to work on will assign that

**Comment by Hemu21** [comment]
@RohitGupta1237  I want to work on backend.

**Comment by RohitGupta1237** [comment]
issue 213 and 214

**Comment by RohitGupta1237** [comment]
@Hemu21  issue 213 and 214
