### ISSUE TITLE
[bug] if after successful payment account is not created then auto refund should happen

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#189]
if after successful payment account is not created then auto refund should happen to user account

**Comment by ankita685** [comment]
please assign me this under gssoc24

**Comment by RohitGupta1237** [comment]
@ankita685 would u like to contribute any issue in #186 thats are priority right now if possible ?  u can take any part of it will create a new issue of that and assign that part to u

**Comment by Hemu21** [comment]
@RohitGupta1237  can you please assign me.
