### ISSUE TITLE
[Backend] API to Get the influencers data form their Social Handles

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#2]
## Description

- [ ] Create an api in backend which will fetch all the influencer stats from below social handles, club it and then send it to the client.
- facebook
- instagram
- tiktok
- snapchat
- youtube
- twitter

- [ ] It should be an open API(no authentication/authorization) required

Use rapidAPI or any other free api which can give this data - https://rapidapi.com/hub

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign this to me

**Comment by RohitGupta1237** [comment]
i have assigned this to u can u check it

**Comment by Hemu21** [comment]
@RohitGupta1237  stats means. Followers ? or anything else.

**Comment by RohitGupta1237** [comment]
@Hemu21 likes views followers growth engagemnet for each registered influencer social media account

**Comment by RohitGupta1237** [comment]
@Hemu21  like whats month on month growth of a influncer for a specified platform in terms of views likes engagement and all for last 6 month

**Comment by Hemu21** [comment]
@RohitGupta1237  I am try to find any way to fetch the data from the social media. If you know anything can you please tell me.

**Comment by RohitGupta1237** [comment]
@Hemu21 https://rapidapi.com/social-api1-instagram/api/instagram-scraper-api2/playground/apiendpoint_4f4c3199-f234-4978-8d94-ae3ca22aa64e 

something of this kind

**Comment by Hemu21** [comment]
@RohitGupta1237  While using rapid api It will contains fetching limit based on the subscription. Is it ok?

**Comment by RohitGupta1237** [comment]
@Hemu21  how much limit will it support

**Comment by RohitGupta1237** [comment]
@Hemu21 like that api call for each user will be made once in a month other than that will store that data to aoid api calls more ...only when data is needs to be updated next month then only new api call wil be made

**Comment by Hemu21** [comment]
@RohitGupta1237 It's ok but if users increases then the call will also increase. I am think about scalability also. above mentioned different social medias. It many cost more. give me some time I will search all available api and scrapers. If nothing is available we can go with rapid api's.

**Comment by RohitGupta1237** [comment]
@Hemu21 can we use free rapid api that has limited request for starting purpose just to put everything in order for begining later will buy the subscription once its is out ..
