### ISSUE TITLE
[Frontend] Make the ChatInterface Responsive

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#20]
## Description
Currently the frontend components are coded in ReactiveNative as per the figma designs but these are not responsive when run so making them responsive is required

- [ ]  It should work for all the screen sizes.

| Page Name                          | Description                                                   | Assignee       |
|------------------------------------|---------------------------------------------------------------|----------------|
| ChatInterface.js                   | Interface for chat functionality                               |              |

**Comment by TheNikhilRaj** [comment]
In Assignees there i haven't there tagged.

**Comment by Kajol-Kumari** [comment]
@TheNikhilRaj  as the issue is level1 so assigning 2 pages in each of these issues, i hope that's okay for u.

**Comment by TheNikhilRaj** [comment]
okay then i have to make both the pages?
@Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
yes @TheNikhilRaj , both pages together will make `level1` if the changes required will look more, we will upgrade the level

**Comment by TheNikhilRaj** [comment]
okay, but where i can find the figma designs i didn't find it can you help me in this, and also can you give me the brief about step by step for what actually what i have to do, or i can develop my own interface. 
@Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
@RohitGupta1237 can you please help Nikhil with the figma and required inputs?

**Comment by RohitGupta1237** [comment]
@TheNikhilRaj any doubts?

**Comment by TheNikhilRaj** [comment]
> @TheNikhilRaj any doubts?
> @RohitGupta1237 yes what i actually do in this interface and how please explain the step by step process?

**Comment by RohitGupta1237** [comment]
@TheNikhilRaj  give me ur id i will give u access

**Comment by TheNikhilRaj** [comment]
> @TheNikhilRaj  give me ur id i will give u access

TheNikhilRaj

**Comment by RohitGupta1237** [comment]
@TheNikhilRaj  gmail?

**Comment by RohitGupta1237** [comment]
@TheNikhilRaj  able to see ? figma

**Comment by TheNikhilRaj** [comment]
> @TheNikhilRaj  able to see ? figma

But I can seen it you have provided the link above

**Comment by RohitGupta1237** [comment]
@TheNikhilRaj so all good now?

**Comment by TheNikhilRaj** [comment]
@RohitGupta1237 i have send the request please accept it ASAP.

**Comment by RohitGupta1237** [comment]
@TheNikhilRaj where?

**Comment by RohitGupta1237** [comment]
@TheNikhilRaj  are u working on this ? issue

**Comment by TheNikhilRaj** [comment]
> @TheNikhilRaj  are u working on this ? issue

@RohitGupta1237 No
