### ISSUE TITLE
[backend]create a api to get list of all collab posted by brands .

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#214]
to get list of all openings posted by brnads from database

**Comment by Hemu21** [comment]
@RohitGupta1237 can you please assign me

**Comment by Hemu21** [comment]
@RohitGupta1237  ok.

**Comment by Hemu21** [comment]
@RohitGupta1237  In this issue you mean all collab opening by all brands or collab openings by specific brand?

**Comment by RohitGupta1237** [comment]
all by all

**Comment by Hemu21** [comment]
@RohitGupta1237  ok.
