### ISSUE TITLE
[Frontend] Make Analytics page Responsive

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#22]
## Description
Currently the frontend components are coded in ReactiveNative as per the figma designs but these are not responsive when run so making them responsive is required

- [ ]  It should work for all the screen sizes.

| Page Name                          | Description                                                   | Assignee       |
|------------------------------------|---------------------------------------------------------------|----------------|
| Analytics.js                   | Displays analytics data                               |                |

**Comment by shivamgaur99** [comment]
@Kajol-Kumari Could you please assign this to me?

**Comment by Kajol-Kumari** [comment]
Hey @shivamgaur99 can't assign more than 3 issues as time, please complete assigned one :)

**Comment by Asymtode712** [comment]
@Kajol-Kumari @RohitGupta1237 Please assign me this issue, I want to work on it

**Comment by RohitGupta1237** [comment]
@Asymtode712 hey assigned you this issue .

**Comment by RohitGupta1237** [comment]
@Asymtode712  hey any updates with this task
