### ISSUE TITLE
[Frontend] Make BrandAccountReviewNotification page  Responsive

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#23]
## Description
Currently the frontend components are coded in ReactiveNative as per the figma designs but these are not responsive when run so making them responsive is required

- [ ]  It should work for all the screen sizes.

| Page Name                          | Description                                                   | Assignee       |
|------------------------------------|---------------------------------------------------------------|----------------|
| BrandAccountReviewNotification.js                   | Notification for brand account review                             |                |

**Comment by shivamgaur99** [comment]
@Kajol-Kumari Could you please assign this to me?

**Comment by Kajol-Kumari** [comment]
Hey @shivamgaur99 can't assign more than 3 issues as time, please complete assigned one :)
