### ISSUE TITLE
[Frontend] Make BrandRegistrationForm  Responsive

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#24]
## Description

- [ ]  It should work for all the screen sizes and should be properly alligned 

| Page Name                          | Description                                                   | Assignee       |
|------------------------------------|---------------------------------------------------------------|----------------|
| BrandRegistrationForm.js                   | Form for brand registration                            |                |

**Comment by Vidip-Ghosh** [comment]
Please assign this issue.

**Comment by BHS-Harish** [comment]
Hello @Kajol-Kumari  @RohitGupta1237 

Still this issue exists..?

**Comment by RohitGupta1237** [comment]
@BHS-Harish  yes it exists

**Comment by BHS-Harish** [comment]
Okay @RohitGupta1237  Assign me the issue .. Is it okay to make responsive as like as the Login Pages...?

**Comment by RohitGupta1237** [comment]
@BHS-Harish  yes it will work

**Comment by RohitGupta1237** [comment]
@BHS-Harish would it be possible to wrap it early

**Comment by BHS-Harish** [comment]
Yeah... I will start immediately...

**Comment by RohitGupta1237** [comment]
@BHS-Harish  are u up for more tasks like this?

**Comment by BHS-Harish** [comment]
Yes I'm interested

**Comment by RohitGupta1237** [comment]
done and fixed
