### ISSUE TITLE
[Frontend] Make FailedPaymentStatus and AccountCreatedSuccessfullyNoti pages Responsive

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#25]
## Description
Currently the frontend components are coded in ReactiveNative as per the figma designs but these are not responsive when run so making them responsive is required

- [ ]  It should work for all the screen sizes.

| Page Name                          | Description                                                   | Assignee       |
|------------------------------------|---------------------------------------------------------------|----------------|
| FailedPaymentStatus.js                   | Notification for failed payment status                            |                |
| AccountCreatedSuccessfullyNoti.js                   | Notification for successful account                               |                |

**Comment by shivamgaur99** [comment]
@Kajol-Kumari Could you please assign this to me?

**Comment by BHS-Harish** [comment]
Hey @RohitGupta1237 

Please assign me the issue
