### ISSUE TITLE
Readme file

### ISSUE THREAD

**Issue by vedi9969** [Kajol-Kumari/InfluMart#258]
I would like to update the readme file by adding setup and installation process like how they can clone the project, how to make PR in project and so  on many such things so the contributors can know how to do it. It will help many other who visits the project.  Below I've attached the image please refer it.
![2](https://github.com/user-attachments/assets/a9f43b9f-f842-4657-9206-69aba0ddcb2d)

**Comment by Kajol-Kumari** [comment]
It already present in the respective backend/frontend folder’s readme
