### ISSUE TITLE
[Frontend] Make HomePage and InfluencerRegistrationForm pages Responsive

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#26]
## Description
Currently the frontend components are coded in ReactiveNative as per the figma designs but these are not responsive when run so making them responsive is required. in influencer registration form when someone clicks + to enter their social media handle then a popup input should appear to enter the handle and and verify button and when user clicks price '->' sign  then again a popup to enter input value and a dropdown for choosing location and industry assosciaiton should be a a input field while others boxes are tickables like age .The bottom bar and menu bar  should be fixed and should not be scrollable while the other part of page should be scrollable.

- [ ]  It should work for all the screen sizes.

| Page Name                          | Description                                                   | Assignee       |
|------------------------------------|---------------------------------------------------------------|----------------|
| Homepage.js                        | Main homepage of the application                               |                |          |
| InfluencerRegistrationForm.js      | Form for influencer registration                               |                |

**Comment by shivamgaur99** [comment]
@Kajol-Kumari please assign me

**Comment by RohitGupta1237** [comment]
@shivamgaur99 description has been updated for more clarity on task

**Comment by RohitGupta1237** [comment]
@shivamgaur99  any doubts with task ?

**Comment by shivamgaur99** [comment]
@RohitGupta1237 No doubt, thank you for asking. 

 `Homepage.js ` making responsiveness done  

`InfluencerRegistrationForm.js`  is in progress

**Comment by shivamgaur99** [comment]
@RohitGupta1237 .The bottom bar and menu bar are sticky now and home page is responsive for all device
![image](https://github.com/Kajol-Kumari/InfluMart/assets/128178418/dbb26830-c743-4b7c-90d0-fab545bfe4b4)

**Comment by RohitGupta1237** [comment]
@shivamgaur99  is this page compatibel with all screen sizes na ?

**Comment by shivamgaur99** [comment]
> @shivamgaur99 is this page compatibel with all screen sizes na ?

yes

**Comment by RohitGupta1237** [comment]
@shivamgaur99  hey any idea about how much time this issue gonna take?

**Comment by RohitGupta1237** [comment]
@shivamgaur99 any doubts?

**Comment by RohitGupta1237** [comment]
@shivamgaur99  are u working on any task ?

**Comment by shivamgaur99** [comment]
@RohitGupta1237 sorry i was up to something so task has not been completed yet, but currently i am  working

**Comment by RohitGupta1237** [comment]
@shivamgaur99  how much time expectedly its gonna take

**Comment by shivamgaur99** [comment]
> @shivamgaur99 hey any idea about how much time this issue gonna take?

@RohitGupta1237 by tomorrow or before, i will make pr

**Comment by RohitGupta1237** [comment]
@shivamgaur99  it should be a dropdown

**Comment by shivamgaur99** [comment]
@RohitGupta1237 task has been completed, need some minor changes regarding style and responsiveness

**Comment by shivamgaur99** [comment]
@RohitGupta1237 Please look at InfluencerRegistrationForm.js, someone made some changes to it and now I am confused about which changes I should accept.
