### ISSUE TITLE
ui changes 

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#270]
button color of login successfull notification has different blue color make it same as other blue button on app
<img width="812" alt="Screenshot 2024-07-17 at 5 26 30 PM" src="https://github.com/user-attachments/assets/5105eb56-68ab-4ce1-b2d5-ea08e5d59bdb">

use this same blue color for them

**Comment by siddharthisrani** [comment]
Hii @RohitGupta1237 Working on it
