### ISSUE TITLE
[frontend] influencer registartion

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#271]
when influcner upload its image we will show a list of avtars if he wanted to choose for them to use as dp now they are randomly shwing and assigning them ...so to fix it we wil show kist and if he choose that then we will save them

**Comment by BHS-Harish** [comment]
@RohitGupta1237 

Assign me the issue

**Comment by lovelymahor** [comment]
@RohitGupta1237 Can you please assign this issue i want to work on this
