### ISSUE TITLE
ui and minor fixes

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#278]
voucher is cutting in app responsiveness issue   collabform file
categories menu is not closing automatiocally when other field is clicked its getting closed on when cross is pressed in collabform and brandtype registration form.
![PHOTO-2024-07-18-11-30-21](https://github.com/user-attachments/assets/86d549e8-e252-4682-a85b-a51d0858bd78)
![PHOTO-2024-07-18-11-31-23](https://github.com/user-attachments/assets/b232a3cd-093c-47fd-96d9-27409cd1d672)

**Comment by BHS-Harish** [comment]
@RohitGupta1237 

Assign me the issue

**Comment by lovelymahor** [comment]
@RohitGupta1237 Can you please assign this issue i want to work on this
