### ISSUE TITLE
bug: Input fields not working

### ISSUE THREAD

**Issue by Vidip-Ghosh** [Kajol-Kumari/InfluMart#28]
https://github.com/Kajol-Kumari/InfluMart/assets/91741581/11a9f926-2bda-440b-9667-591e331da77e

Whenever I try to click an input field, it doesn't display keyboard.

**Comment by Vidip-Ghosh** [comment]
Expected Behaviour: 

https://github.com/Kajol-Kumari/InfluMart/assets/91741581/dfaf112e-ae27-4c4b-b6a3-ba7f51fb8c48

**Comment by Kajol-Kumari** [comment]
@Vidip-Ghosh can you please fix this under https://github.com/Kajol-Kumari/InfluMart/issues/24 as we already have the respective pages issue opened now to get it fixed and responsive.

P.S - regarding the level of the issue, we might upgrade ut based on the complexity seen during development

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh can you please fix this under #24 as we already have the respective pages issue opened now to get it fixed and responsive.
> 
> P.S - regarding the level of the issue, we might upgrade ut based on the complexity seen during development

Okay sure. I'll
