### ISSUE TITLE
[Bug] Multiple Issues to fix

### ISSUE THREAD

**Issue by Hemu21** [Kajol-Kumari/InfluMart#280]
## Description:
1. Status Bar not visible
2. Search not working
3. No hint text in Gender
4. Gender should have option other and prefer not to say
5. Country picker cannot be closed

Fixing all mentioned above issues.

**Comment by Hemu21** [comment]
@RohitGupta1237  can you please assign me.

**Comment by lovelymahor** [comment]
@RohitGupta1237 Can you please assign this issue i want to work on this
