### ISSUE TITLE
Footer is Required

### ISSUE THREAD

**Issue by lovelymahor** [Kajol-Kumari/InfluMart#281]
We need to implement a footer for our website to enhance navigation and provide essential information at the bottom of every page.

Content:

Company Information: Brief about us, contact details.
Navigation Links: Quick links to important pages (e.g., Home, About Us, Services, Contact).
Social Media Icons: Links to our social media profiles.
Newsletter Signup: Option for users to subscribe to our newsletter.
Copyright Notice: © [Year] [Company Name]. All rights reserved.

Please assign it to me I want to work on this issue. Also, please add the label GSSOC and the level that you find appropriate for this issue. thank you!

**Comment by RohitGupta1237** [comment]
@lovelymahor  hey we have 2 days to wrap this issue if u can do that in this time frame pls

**Comment by lovelymahor** [comment]
@RohitGupta1237 should I complete this or not??
