### ISSUE TITLE
{Feature] Add a feature where user should enter valid email id

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Kajol-Kumari/InfluMart#283]
![Screenshot 2024-07-19 020602](https://github.com/user-attachments/assets/b3b4409e-8684-4343-89bd-42b4441a040f)

Here email id is not valid still it is taken as an input

**Comment by Kajol-Kumari** [comment]
@Ishitamukherjee2004  closing this as its covered under https://github.com/Kajol-Kumari/InfluMart/issues/297 ping in the issue if u are interested in 297
