### ISSUE TITLE
[Frontend] Integrate the analytics Graph on Influencers Profile

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#29]
##Description

- [ ] Currently, the influencer data is static, as we already have the social handle data in our DB during signup, use it show on the profile page in the form of graphs
- [ ] Each Social handle should have their respective graph, so provide a dropdown for the same in the influencer profile so that anyone can see analytics of which social media profile you want to see

Current Profile Page where the integration needs to be done - https://drive.google.com/file/d/1Xr1hQChCcPjcX1pb3noJRr5FQvUu_rnS/view?usp=sharing

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign this to me.

**Comment by RohitGupta1237** [comment]
@Hemu21  any doubt with this ? issue

**Comment by RohitGupta1237** [comment]
@Hemu21  hey mailed you instagram and youtube statistics end point
