### ISSUE TITLE
Adding new logo for InfluMart

### ISSUE THREAD

**Issue by Maheshwari-Love** [Kajol-Kumari/InfluMart#293]
I want to add new Logo for this project

**Comment by Maheshwari-Love** [comment]
@RohitGupta1237 can you please assign me this task

**Comment by Maheshwari-Love** [comment]
@RohitGupta1237 can you please assign labels

**Comment by Kajol-Kumari** [comment]
@Maheshwari-Love based on your proposals we can upgrade the level later if required

**Comment by RohitGupta1237** [comment]
@Maheshwari-Love this issue is not needed repo
