### ISSUE TITLE
[Frontend] Fix UI Hiccups

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#298]
## Description
There are list of UI hiccups which is giving bad experience to the user, fix these below listed issues - 

<img width="565" alt="Screenshot 2024-07-22 at 1 02 58 AM" src="https://github.com/user-attachments/assets/7da41924-96cc-454c-b61a-a46e19f85385">

- [ ] When user tries to select their country code, there is no way they can close the pop-up if they want to go back, Add a close button/icon which can allow the users to close the pop-up
- [ ] The `influencerType` list and the `Gender Selection` list opens a drop-down, that dropdown should auto-close if user click on any other input boxes
<img width="562" alt="Screenshot 2024-07-22 at 1 04 59 AM" src="https://github.com/user-attachments/assets/637a0171-1def-40ed-8f2e-8f1f59d8412e">

- [ ] The location pop-up should appear similar to the country-code pop-up for the phone number, there should be search box and a cross icon/button in the same row. Current UI is in't in sync.

<img width="566" alt="Screenshot 2024-07-22 at 1 06 07 AM" src="https://github.com/user-attachments/assets/9ab9099c-1e70-47c4-bc42-0c66cffaa47a">

- [ ] In influencer's registration form, there is a lot inconsistency in margin/padding which is making the UI look bad, fix it to use the standard, common margin/padding across the form
<img width="585" alt="Screenshot 2024-07-22 at 1 16 53 AM" src="https://github.com/user-attachments/assets/055aa7dc-3c83-42ea-aa00-428bebe247de">

**Comment by BHS-Harish** [comment]
@RohitGupta1237 @Kajol-Kumari 

Assign me the issue
