### ISSUE TITLE
[Frontend] Brand SignUp UI Enhancement 

### ISSUE THREAD

**Issue by Hemu21** [Kajol-Kumari/InfluMart#31]
## Description

This Includes the brand registration form, otp verifictaion, preview. Here I am want to make those fields to interact. With this ui enhancement The brand sign up is completly ready with all funtionality and features.

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign this to me.

**Comment by Kajol-Kumari** [comment]
@Hemu21  couple of more things to include while fixing - 

- [ ] The `BrandType` dropdown should have the values i listed in you rprevious pr
- [ ] The button in registration form should be `Sign Up` , currently its `signIn`
