### ISSUE TITLE
[Frontend] Make Admin Panel Responsive 

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#32]
Currently the frontend components are coded in ReactiveNative as per the figma designs but these are not responsive when run so making them responsive is required. Admin panel involves functionalities for user to update passwords and other information related to account.

 It should work for all the screen sizes.

**Comment by shivamgaur99** [comment]
@RohitGupta1237 Could you please assign this to me?

**Comment by RohitGupta1237** [comment]
@shivamgaur99 hey have are u done with  that previous task?

**Comment by shivamgaur99** [comment]
@RohitGupta1237  i had done with responsiveness only and left it to add to popup functionality

**Comment by RohitGupta1237** [comment]
@shivamgaur99 input fields working ?

**Comment by RohitGupta1237** [comment]
@shivamgaur99 if u can raise pr for that

**Comment by shivamgaur99** [comment]
@RohitGupta1237, the addition of the popup functionality is pending. i will make pr soon

**Comment by BHS-Harish** [comment]
Hey @RohitGupta1237 

Please assign me the issue
