### ISSUE TITLE
[Backend] Forget&Reset Password Functionality for Brand and Influencers

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#37]
## Description

- [ ] Create an API in backend which will help the influencer/brand to **reset** their password.
- [ ] Make sure to have the authorization check so that the brand/influencer can only reset their own password, maybe otp on email can help to achieve the same.(I am all ears to hear about better method)
----------------------------------------------------------------------------------
- [ ] Create one more API in backend which will help the influencer/brand to **update** their password.
- [ ] Verify their token and the body of reset will be `currentPassword, newPassword`, so make sure you match the currentPassword value existing in the db before updating it.

**Comment by BHS-Harish** [comment]
Hey @Kajol-Kumari  @RohitGupta1237 

I'm interested to work on the issue.

**Comment by RohitGupta1237** [comment]
@BHS-Harish hey any doubt with the task?

**Comment by BHS-Harish** [comment]
> @BHS-Harish hey any doubt with the task?

Now not @RohitGupta1237 
I'm currently working on another issue and once i completed that, i will work on this issue.

**Comment by Shivam2534** [comment]
Hello Sir,

My name is Shivam Kanchole, and I am a fourth-year student at IIT Roorkee. I find this issue both interesting and challenging. Additionally, I have worked on similar projects in the past. Could you please assign this issue to me?

Thank you.

Best regards,
Shivam Kanchole

**Comment by RohitGupta1237** [comment]
@Shivam2534  hey assigned you this ..u can work on this ...happy learning

**Comment by RohitGupta1237** [comment]
@Shivam2534 hey can u work on this issue first as #11 issue is completed already

**Comment by Kajol-Kumari** [comment]
@BHS-Harish can u please confirm if u are working on this issue?

**Comment by BHS-Harish** [comment]
Hello @Kajol-Kumari  I'm not started..

If @Shivam2534 Interested on the issue, kindly assign him.

**Comment by RohitGupta1237** [comment]
@Shivam2534 hey any doubts with issue ?

**Comment by Shivam2534** [comment]
Not yet

**Comment by RohitGupta1237** [comment]
@Shivam2534 hwy how much expected time this gonna take?

**Comment by UtkarshBirla28** [comment]
@RohitGupta1237 Assign it to me my exams are over so i will resolve it ASAP.

**Comment by Kajol-Kumari** [comment]
@UtkarshBirla28 can you take this issue ASAP?

**Comment by UtkarshBirla28** [comment]
@Kajol-Kumari Yah sure

**Comment by RohitGupta1237** [comment]
@UtkarshBirla28 hey any updates ? any doubts

**Comment by UtkarshBirla28** [comment]
@RohitGupta1237 i will start from today

**Comment by RohitGupta1237** [comment]
@UtkarshBirla28  hey try to wrap this today only we r short of time pls

**Comment by UtkarshBirla28** [comment]
@RohitGupta1237 sure

**Comment by UtkarshBirla28** [comment]
@RohitGupta1237 i have a question 

i have setuped everything backend , frontend, DB but ur login and signup pages r not working at all

so i have made some mistakes or these pages r not working ??

![Screenshot (130)](https://github.com/Kajol-Kumari/InfluMart/assets/96072228/705db26c-ee27-4232-be41-ddc38f264d9c)


Ig i have to use postman for authentications

**Comment by RohitGupta1237** [comment]
@UtkarshBirla28  login page username not email to login

**Comment by RohitGupta1237** [comment]
Can we connect on meet for 5 mins u will get idea how it’s working

**Comment by UtkarshBirla28** [comment]
![Screenshot (131)](https://github.com/Kajol-Kumari/InfluMart/assets/96072228/b09b6b38-b373-44b6-84d1-b10c4e339bd9)
seee

**Comment by UtkarshBirla28** [comment]
> ![Screenshot (131)](https://private-user-images.githubusercontent.com/96072228/344465156-b09b6b38-b373-44b6-84d1-b10c4e339bd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NTA5NDUsIm5iZiI6MTcxOTc1MDY0NSwicGF0aCI6Ii85NjA3MjIyOC8zNDQ0NjUxNTYtYjA5YjZiMzgtYjM3My00NGI2LTg0ZDEtYjEwYzRlMzM5YmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDEyMzA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZDVkMDMzYTgyZTIzMDYwOWJjMDk2NDQ2MDJhZmEwY2NjMmFiNGZiYTk1N2QxOGRmZTY4YTUyYWFmM2I0MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NgUEofvh4MiUuVR4eJYPJpcz3yVk-7dFA3SIONjedB4) seee

request is not going

**Comment by RohitGupta1237** [comment]
@UtkarshBirla28 
<img width="1440" alt="Screenshot 2024-06-30 at 6 03 49 PM" src="https://github.com/Kajol-Kumari/InfluMart/assets/97328133/c140ccd3-4dcd-426f-bfc5-4033dc02b7c4">


its working here

**Comment by UtkarshBirla28** [comment]
@RohitGupta1237 ha on netlify it is working but on my local it's not 
![Screenshot (132)](https://github.com/Kajol-Kumari/InfluMart/assets/96072228/7e90aa4b-e772-4724-b9b4-c32e7bbd7a00)
backend is also connected

**Comment by UtkarshBirla28** [comment]
and DB is also running 
![Screenshot (133)](https://github.com/Kajol-Kumari/InfluMart/assets/96072228/8f787c22-8c61-4969-bd67-e92a05620956)
seee

**Comment by UtkarshBirla28** [comment]
@RohitGupta1237 I am sorry but assign it to someone else .

**Comment by Hemu21** [comment]
@RohitGupta1237  can you please assign this to me.
