### ISSUE TITLE
[Frontend] Making BrandAssociated pages responsive.

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#39]
Currently the frontend components are coded in ReactiveNative as per the figma designs but these are not responsive when run so making them responsive is required. This page involves list of all those brands that are registered on our platform.

It should work for all the screen sizes.

**Comment by shivamgaur99** [comment]
@RohitGupta1237 Could you please assign this to me?

**Comment by RohitGupta1237** [comment]
@shivamgaur99  are u upto some thing?

**Comment by BHS-Harish** [comment]
Hey @RohitGupta1237 

Please assign me the issue.

**Comment by RohitGupta1237** [comment]
@BHS-Harish  hey assigned

**Comment by RohitGupta1237** [comment]
@BHS-Harish in this menu bar and bottom bar should not be scrolling they should be fixed ...rest page should be scrolling

**Comment by BHS-Harish** [comment]
what about the top bar..?

**Comment by RohitGupta1237** [comment]
closed with #69
