### ISSUE TITLE
[Backend] Get Subscription Charges API

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#4]
## Description
Create an API, which will show the subscription charge based on below logic.

From the social stat, take out the max follower - 
For a quarter -> ((80% of the number of followers)*(0.50) / 12) *3  + 20% of ((80% of the number of followers)*(0.50) / 12)*3 
For 6 months -> ((80% of the number of followers)*(0.50) / 12) *6 + 10% of ((80% of the number of followers)*(0.50) / 12)*6 
For a year ->((80% of the number of followers)*(0.50))

Dependent upon - https://github.com/Kajol-Kumari/InfluMart/issues

**Comment by Hemu21** [comment]
@Kajol-Kumari  or @RohitGupta1237  can you please assign this to me.
