### ISSUE TITLE
[Backend] A messaging platform between brands and influencers to connect

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#40]
A messaging platform between brands and influencers to connect on the portal. to message influecners first a brand is required to request influencer to connect with influencer once the influencer accepts the request then a hi message will be sent to both brand and influcner  after that the message functionality will work and both can chat on platform and after successful deal anyone can close that chat and once anyone clicks on close the chat then no more chatting can be done with that user and if they want to connect again then same procedure will follow. The life of messgae will be 3 days ...after three days the messgwes will be deleted.
 Chat and inbox folder in code contains ui  static designs

**Comment by Hemu21** [comment]
@RohitGupta1237  can you please assign me.
