### ISSUE TITLE
[Bug] The Brand Login and Signup Not as expected

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#44]
## Description
There is couple of issues in brand login and signup that needs to be fixed 

- [ ] After brand signup, the password is getting stored as plain text in db, it should be hashed just like we are doing for influencer
- [ ] The login for brand is not working (its probably 'coz of the unhashed password getting saved in db but this needs fix)

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign me

**Comment by Hemu21** [comment]
Login will be fixed with my previous pr.

**Comment by Kajol-Kumari** [comment]
@Hemu21 even the login logic will have the decryption logic added after adding encryption during save password
