### ISSUE TITLE
Creating Filtering and searching functionality for list of influencers 

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#46]
Brand can search and  filter list of influencers based on following filters like 
1. location they entered in registration form, 
2. category they choose   , 
3. price then they will choose platform then sleect price for marketing for different platform
4. Based on tags they have in analytics  , 
5. followers/subscribers then choose platform then followers , 
6. similar to followers do same for likes , 
7. based on engagement. rate , 
8. brands will select age of their audience then we will show list of influncers in decreasing order having maximum percentage viewers belonging to that age 
10. Gender
11. Reachability 
12.  avg commnets 
13. views count 
14. cities viewers belong to if viership is > 1% then show those influners in that list 
all this data we will be having for influencer in data base .

**Comment by sanjay-kv** [comment]
@Kajol-Kumari Hi , I need access to the repo. there are some label related issue I need to fix.

**Comment by RohitGupta1237** [comment]
@sanjay-kv hey are u willing to contribute to this project

**Comment by sanjay-kv** [comment]
@RohitGupta1237 im Program manager, admin was not replying to emails so randomly selected an issue to raise the concern.

**Comment by Manaswini123456** [comment]
@RohitGupta1237 I'll try to implement the solution as soon as possible. Thank you for the opportunity.

**Comment by sanjay-kv** [comment]
@RohitGupta1237 I need access to the repo to manage labels, could you add me. Im PM of gssoc.

**Comment by RohitGupta1237** [comment]
@sanjay-kv  This influmart repo access?

**Comment by sanjay-kv** [comment]
yes @RohitGupta1237 , i just need basic access just for manage labels. i think `write` will do

**Comment by Manaswini123456** [comment]
@RohitGupta1237 Would provide my insights, by within 3 days. I hope the timeline is ok?

**Comment by RohitGupta1237** [comment]
@Manaswini123456 yes its fine , hope this issues gets wrap up soon

**Comment by Manaswini123456** [comment]
@RohitGupta1237 Thank you so much. Will do the needful.

**Comment by Manaswini123456** [comment]
@RohitGupta1237 Due to unwanted circumstances, I won't be able to contribute to the particular issue, I kindly request you to unassign me from this issue, and provide the same to some other contributor. Thank you so  much for the opportunity.

**Comment by Ayushmaanagarwal1211** [comment]
@Kajol-Kumari  I want to work on this issue can you please assign this to me

**Comment by RohitGupta1237** [comment]
@Ayushmaanagarwal1211 hey assigned would it be possible for u to wrap this we have 1 day only we r short of time pls

**Comment by Ayushmaanagarwal1211** [comment]
Ya sure i am starting working on it

**Comment by Ayushmaanagarwal1211** [comment]
@RohitGupta1237  sir if i understand the issue clearly then when i go to influencers page then the influencers must be filter out according to the given dropdown selections 

https://github.com/Kajol-Kumari/InfluMart/assets/118350936/073d07e7-0035-434e-999e-1c8042ad7564

**Comment by RohitGupta1237** [comment]
@Ayushmaanagarwal1211 hey there is a filter button based on which selection of influcners would be done like no of followers ,  place of viewrs , age of viewers , typw of content , likes , followerts etc .

**Comment by RohitGupta1237** [comment]
@Ayushmaanagarwal1211  hey any updates?

**Comment by Ayushmaanagarwal1211** [comment]
@RohitGupta1237  yes sir actually i am not much familiar with React native and also need much details for setting up the backend i am understanding the code i am trying to do that but in the mean time you can also assign other member as well we can work together

**Comment by Freakrish** [comment]
Can you assign me this issue?

**Comment by RohitGupta1237** [comment]
@Freakrish  we have time for todays evening would it be pssible to make it by that time please ...we are little short of time

**Comment by RohitGupta1237** [comment]
@Freakrish  hey any doubts any updates?

**Comment by RohitGupta1237** [comment]
@Freakrish any upddate?

**Comment by Freakrish** [comment]
Sir, Got caught up in some issues. Give me 2 days max

**Comment by Hemu21** [comment]
@RohitGupta1237 can you please assign me
