### ISSUE TITLE
[Frontend+Backend] Creating About us and contact us pages

### ISSUE THREAD

**Issue by r7projects-shayan** [Kajol-Kumari/InfluMart#48]
There is currently no About Us and Contact Us page. 

I will create minimalistic about us and contact us pages with form validation and send details to owner functionality. It will be a complete user management system, where you will receive the results of the filled form directly to a database.

**Comment by r7projects-shayan** [comment]
@Kajol-Kumari Kindly assign me this huge issue to work on. it needs to get tackled soon for the website to stand out

**Comment by RohitGupta1237** [comment]
@r7projects-shayan  who give u access to this repo..?

**Comment by r7projects-shayan** [comment]
> @r7projects-shayan who give u access to this repo..?

gssoc website

**Comment by RohitGupta1237** [comment]
@r7projects-shayan  its not gssoc repo

**Comment by Kajol-Kumari** [comment]
@r7projects-shayan we aren't looking for anything extra apart from the basic mvp so closed this issue.
