### ISSUE TITLE
[Backend] A api to keep track of collaborations between brands and influencers

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#49]
- [ ] API to keep record of no of collaborations done by brands on the portal and  keeping the record of all the collaborations done by brand which includes whats the average growth value of followers , post frequency which means no of posts they post in a month , whats average engagement rate they look that comes after analysing all the deals brand made with influencers ...that they look for dealing with influencer. 

- [ ] API to track record of minimum followers brand look in influencer. , average minimum likes and post frequency...in above api we track all collaborations and analyse them and then show insights whereas in this only we will look for minimum requirements which is usually the lowest data of all collaboration the brand had dealed with influencer.

for better reference look brand profile page in updated sample video

**Comment by Asymtode712** [comment]
@RohitGupta1237 @Kajol-Kumari I want to work on this issue, please assign it to me

**Comment by RohitGupta1237** [comment]
@Asymtode712  hey assigned u this issue ...hey would it be possible for u to fix this issue at a faster pace please.

**Comment by Asymtode712** [comment]
Sure will give you an update soon
