### ISSUE TITLE
[Frontend] Integration of List of influencers api and list of brands api with frontend.

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#54]
When users click search button on bottom bar on home page then list of influencers page will open and when user will click brands button at bottom bar on homepage  then list of all brands registered with us will open. Keep the css same.

**Comment by BHS-Harish** [comment]
Hello @RohitGupta1237  @Kajol-Kumari 

I'm interested to resolve the issue.
Please assign it to me

**Comment by RohitGupta1237** [comment]
@BHS-Harish  hey assigned u this

**Comment by Hemu21** [comment]
@RohitGupta1237  can you please assign this to me.
