### ISSUE TITLE
[Frontend] Making brandorInfluencer and otp verification page responsive 

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#56]
It should work for all the screen sizes and should be properly aligned .

**Comment by BHS-Harish** [comment]
Hello @RohitGupta1237 

Assign me the issue

**Comment by RohitGupta1237** [comment]
@BHS-Harish hey assigned

**Comment by BHS-Harish** [comment]
Okay @RohitGupta1237  Thanks
