### ISSUE TITLE
[Frontend] making BrandAccountSignupDataPreview.js page responsive 

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#58]
BrandAccountSignupDataPreview alignment and responsiveness and the place where image is ...it should have option for brand to upload brand dp.

**Comment by BHS-Harish** [comment]
Hey @RohitGupta1237 

May i know the flow of the Brand Signup..?

**Comment by RohitGupta1237** [comment]
@BHS-Harish  meet? can we connect on meet for 5 min now

**Comment by RohitGupta1237** [comment]
@BHS-Harish  https://drive.google.com/file/d/1dqYtn5pUatQ0UQ0HrHkRVzIG4r_G6-ID/view?usp=sharing
 
see this video for reference .. brand will click on signup then registration form for brand will open then he will put his information then he will click generate otp once the otp is received and verified then BrandAccountSignupDataPreview page will open showcasing the information entered in brandregistrationform then he will check his information then click on create account button and accoutn will be created

**Comment by RohitGupta1237** [comment]
@BHS-Harish Hey u dont have to store dp for now just make that such that there is option to save dp..currently we are not saving dp in database ...will do that after this for now instead of photo just provide there a way to uplad dp kinda thing >>

can we connect on meet ?

**Comment by BHS-Harish** [comment]
Yes we can

**Comment by RohitGupta1237** [comment]
@BHS-Harish  https://meet.google.com/jon-jijy-khz
