### ISSUE TITLE
[Frontend] making FriendRequestPage.js page responsive

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#6]
## Description
 Currently the frontend components are coded in ReactiveNative as per the figma designs but these are not responsive when run so making them responsive is required

**NOTE - Each of these pages will have respective level1/level0 attached to it based on which page u choose**

| Page Name                          | Description                                                   | Assignee       |
|------------------------------------|---------------------------------------------------------------|----------------|
| FriendRequestPage.js               | Page displaying friend requests                                |                |

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me (ChatInterface.js).
@Kajol-Kumari @RohitGupta1237 @Hemu21

**Comment by RohitGupta1237** [comment]
@TheNikhilRaj Hey I have assigned you this task please go ahead with this issue.

**Comment by TheNikhilRaj** [comment]
Thank you for assigning i choose the issue page "ChatInterface.js" can you tell me what's the level i got from this issue,
NOTE - Each of these pages will have respective level1/level0 attached to it based on which page u choose
@RohitGupta1237

**Comment by RohitGupta1237** [comment]
@TheNikhilRaj Level 1

**Comment by Kajol-Kumari** [comment]
@TheNikhilRaj please feel free to open a new issue for the assigned folder so that it gets properly counted under gssoc

**Comment by BHS-Harish** [comment]
@RohitGupta1237 
Assign me the issue
