### ISSUE TITLE
[Frontend] Adding alert notifications 

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#65]
Whenever any events happens showing the notification alerts for  the event 
1. if username already exists then alert to show that user is already registered
2. when otp is send successfully or not send successfully ,  Successful /unsuccessful sending of otp alert 
3. verification of otp if otp is successfully verifed or failed to verify otp
4. if password entered is incorrect while logging in for brands or influencer 
5. successful sending of friend request 
6. successful accptance of friend request 
7. if login is failed due to any connectivity issue or other issue showing alert for this .
8. if signup is failed for any issue whether any connectivity issue or verification issue

**Comment by Hemu21** [comment]
@RohitGupta1237  can you please assign this to me.
