### ISSUE TITLE
[Frontend] Creating a connect request api at backend 

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#66]
When brand clicks on connect with influencer button in Analytics.js File then the request notification must appear in userprofile.js and when user clicks on view request then he can see complete request like in FriendRequestPage.js and once the notification is accepted then a hello message will be automatically sent to both brand and influencr . There will be no count or record of followers in either of profiles only a hi nessage in messaging system will be indication of successful acceptance of notification after which users can chat on the messaging platform .. this issue deals with that request system only .

**Comment by Hemu21** [comment]
@RohitGupta1237 can you please assign this to me.
