### ISSUE TITLE
[Frontend] Add the Form Validations and username Unique Validations

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#67]
- [ ] Add the email validation in login and signup form 
- [ ] Add an eye icon in password field which user can use to check and verify their password
- [ ] The username unique check needs to be added

**Comment by shivamgaur99** [comment]
Hi @Kajol-Kumari, I've completed the 2nd task. Regarding the recent PR, I've already added the eye icon to the password field. 
could please assign this to me?

**Comment by JaiBansal007** [comment]
hi @Kajol-Kumari i want to work on this issue .Could you please assign me this issue?
