### ISSUE TITLE
[Frontend] Making InfluencersList.js responsive 

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#70]
In this the influencers brands both etc ..bar should be a slider with clickable buttons and dropdown. the top bar and menu bar should be fixed with bottom bar buttons are clickable and search button should be working like when search button is clicked a search bar of same alignment should open and marketplace title should disappear and profile photo of influencer should appear in same shape . make bottom bars button such that they spacing gets aligned with screen size

**Comment by BHS-Harish** [comment]
Hey @RohitGupta1237 

Assign me the issue.

**Comment by BHS-Harish** [comment]
Hey @RohitGupta1237 

What about the items of dropdown's..?

**Comment by RohitGupta1237** [comment]
@BHS-Harish add any randoms xyz for now

**Comment by BHS-Harish** [comment]
Filter button should be fixed at bottom... Am i right..?

**Comment by RohitGupta1237** [comment]
@BHS-Harish yes it should be fixed but while content is scrolling then its should become translucent

**Comment by RohitGupta1237** [comment]
@BHS-Harish  hey sent on mail
