### ISSUE TITLE
[Backend] Changing Brands and influencer db schema so that profile photo can be saved in db for both 

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#73]
Influencers and brands can save their dp and and upload it in profile . Currently there is no way for brands and influencers to store their profile photo.

**Comment by Hemu21** [comment]
@RohitGupta1237  can you please assign this to me.

**Comment by Hemu21** [comment]
@RohitGupta1237  it includes adding multer and managing the url not only change the db schema. you can make it level3 now or after reviewing the pr. it's better to make label after reviewing pr for this.
