### ISSUE TITLE
[Frontend] Integration Get Profile Page for Brand

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#81]
## Description

- [ ] Complete the GET Profile API - [https://github.com/Kajol-Kumari/InfluMart/blob/main/backend/controllers/brandController.js#L54](https://github.com/Kajol-Kumari/InfluMart/blob/main/backend/controllers/brandController.js#L54)
- [ ] As soon as i log in using emailId and password as brand, I should be seeing my details instead of dummy Data. There should be `Settings` and `inbox` buttons instead of `Follow` and `Message`.
<img width="400" alt="Screenshot 2024-06-24 at 4 36 31 PM" src="https://github.com/Kajol-Kumari/InfluMart/assets/44888949/e8de2888-cbcf-4d9d-aa35-0392324d0a66">

**Comment by Hemu21** [comment]
can you please assignn this to me I am working this page only.
