### ISSUE TITLE
[Backend] Create Missing Brand APIs

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#82]
## Description

- [ ] An API to update the Brand Profile. Make sure the required authentication and authorization
- [ ] And API to delete the Brand Profile. Make sure the required authentication and authorization
- [ ] An open API to fetch the list of all brands(make sure not to include their passwords while fetching)
- [ ] A cron Job API to delete the otps saved under `otp` collection which are older than 1 hour

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign this to me.
