### ISSUE TITLE
[Frontend] Integration the Brand Signup with Backend

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#9]
## Description
Current frontend page is static, integrate the [Brand-Signup](https://github.com/Kajol-Kumari/InfluMart/blob/main/influmartFrontend/screens/BrandRegistrationForm.js) page with the backend API - 
https://github.com/Kajol-Kumari/InfluMart/blob/main/backend/controllers/brandController.js#L7

**Comment by Hemu21** [comment]
@Kajol-Kumari  or @RohitGupta1237  can you please assign this to me.
