### ISSUE TITLE
[Frontend] Integrating payment interface with the app 

### ISSUE THREAD

**Issue by RohitGupta1237** [Kajol-Kumari/InfluMart#90]
When user after choosing plan clicks proceed to payment then payment interface should open specifying amount user selected to pay and once payment is successful the user is re directed to successful registration notification  page.

influencer registration->influencer registartion form-> select plan->proceed to payment ->payment interface->(review page) create account->success

https://razorpay.com/docs/payments/server-integration/nodejs/payment-gateway/build-integration/

**Comment by Hemu21** [comment]
@RohitGupta1237 can you please assign me
