### ISSUE TITLE
[Frontend] Add loader to show the operation/API Call

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#93]
## Description

- [ ] There should be a loader indicating any API call in progress so that user remains aware of it, currently nothing happens during the signIn/signup showing the progress.
- [ ] Add the loader to all the required places

**Comment by RohitGupta1237** [comment]
@AsmitaMishra24 hey issue assigned ..would it be possible for you to wrap this issue asap.

**Comment by RohitGupta1237** [comment]
@AsmitaMishra24  hey sorry to bother but we are quite short of time ...would it be possible to make it priority and do it by thursday evening? please

**Comment by RohitGupta1237** [comment]
@AsmitaMishra24  hey any updates on this

**Comment by AsmitaMishra24** [comment]
> @AsmitaMishra24 hey any updates on this

 Actually, I was busy with college assignments today but I started working on it......I will surely make PR by tomorrow morning.

**Comment by AsmitaMishra24** [comment]
I am getting an error while running the application "API_ENDPOINT" is not defined in .env.

**Comment by AsmitaMishra24** [comment]
@RohitGupta1237, I getting error 500 while running the application...you can reassign the issue if someone wants to work... I am also trying

**Comment by Kajol-Kumari** [comment]
> I am getting an error while running the application "API_ENDPOINT" is not defined in .env.

@AsmitaMishra24 you need to create `.env` file taking reference from `.env.sample` file as there are some environment variables required to run the project

**Comment by BHS-Harish** [comment]
Hey @RohitGupta1237 

Please assign me the issue
