### ISSUE TITLE
[Frontend] Back button should be consistent everywhere

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#94]
## Description

- [ ] Currently, at few places we have back arrow button and some places, just clicking on heading takes back, it should be everywhere back button for moving to previous page.The flow should not be changed nor the alignment , only consistency should be there.

**Comment by RohitGupta1237** [comment]
@rajankonar  hey issue assigned ...would it be possible for u to wrap it fast

**Comment by rajankonar** [comment]
@RohitGupta1237  UI is not consistent

1) At some places, arrow and title comes one below another and in some sections, it comes in a single line.
2) There is margin above header section in some places.

Do you want me to fix this as well in this PR or you will create new PR for these issues?

**Comment by RohitGupta1237** [comment]
@rajankonar  fix them in this pr only keeping responsiveness and flow unaffected

**Comment by Kajol-Kumari** [comment]
@rajankonar it should be consistent everywhere and should be covered in this issue

**Comment by rajankonar** [comment]
Hi @RohitGupta1237 
PR : [https://github.com/Kajol-Kumari/InfluMart/issues/94](94)
