### ISSUE TITLE
[Bug] Profile Picture Not Getting Saved and Login Again & again

### ISSUE THREAD

**Issue by Kajol-Kumari** [Kajol-Kumari/InfluMart#96]
## Description
- [ ] The profile picture isn't getting saved in DB if i select an image during the brand registration
- [ ] After logging in, if i go to back/home page, i again need to signIn, if my token isn't expired, i should be directed to the loggedIn page ideally.
- [ ] When user revisits influencer registration form to make changes then social profile , phot0s etc fields data go reset and he has to reverify them all to go forward ..ideally after completion of process or if user doesnot want to register and w goes back then only fields data should reset ...until then all data should not be lost.
- [ ] Similarly for brands also once user goes back of regsitration form then data should be reset or user completes the process then data should reset

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign this to me.
